/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.form;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/**
 * MyEclipse Struts Creation date: 10-27-2014
 * 
 * XDoclet definition:
 * 
 * @struts.form name="noticeForm"
 */
@Entity
public class NoticeForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String noticetitle;
	private String mytext;
	
	
	

	public String getNoticetitle() {
		return noticetitle;
	}

	public void setNoticetitle(String noticetitle) {
		this.noticetitle = noticetitle;
	}

	public String getMytext() {
		return mytext;
	}

	public void setMytext(String mytext) {
		this.mytext = mytext;
	}

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		ActionErrors errors = new ActionErrors();
		if (getNoticetitle() == null || getNoticetitle().length() < 1) {
			errors.add("noticeTitle", new ActionMessage("error.noticeTitle.required"));
			// TODO: add 'error.username.required' key to your resources
		}
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}