/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.form;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-27-2014
 * 
 * XDoclet definition:
 * @struts.form name="policyupForm"
 */
@Entity
public class PolicyupForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String policytitle;
	private String mytext;
	private String filetitle;
	private FormFile policyfile;	
	

	public String getPolicytitle() {
		return policytitle;
	}

	public void setPolicytitle(String policytitle) {
		this.policytitle = policytitle;
	}

	public String getMytext() {
		return mytext;
	}
	
	public String getFiletitle() {
		return filetitle;
	}

	public void setFiletitle(String filetitle) {
		this.filetitle = filetitle;
	}

	public void setMytext(String mytext) {
		this.mytext = mytext;
	}

	public FormFile getPolicyfile() {
		return policyfile;
	}

	public void setPolicyfile(FormFile policyfile) {
		this.policyfile = policyfile;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}