/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.form;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-27-2014
 * 
 * XDoclet definition:
 * @struts.form name="qualityuploadForm"
 */
@Entity
public class QualityuploadForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	
	private String quatitle;
	private String filetitle;
	private String quatype;
	private FormFile quafile;	

	public String getQuatitle() {
		return quatitle;
	}

	public void setQuatitle(String quatitle) {
		this.quatitle = quatitle;
	}

	public String getFiletitle() {
		return filetitle;
	}

	public void setFiletitle(String filetitle) {
		this.filetitle = filetitle;
	}

	public String getQuatype() {
		return quatype;
	}

	public void setQuatype(String quatype) {
		this.quatype = quatype;
	}

	public FormFile getQuafile() {
		return quafile;
	}

	public void setQuafile(FormFile quafile) {
		this.quafile = quafile;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}