/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.form;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-28-2014
 * 
 * XDoclet definition:
 * @struts.form name="tissuechangeForm"
 */
@Entity
public class TissuechangeForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String thetitle1;
	private FormFile thefile1;
	private String thetitle2;
	private FormFile thefile2;
	private String thetitle3;
	private FormFile thefile3;

	public String getThetitle1() {
		return thetitle1;
	}

	public void setThetitle1(String thetitle1) {
		this.thetitle1 = thetitle1;
	}

	public FormFile getThefile1() {
		return thefile1;
	}

	public void setThefile1(FormFile thefile1) {
		this.thefile1 = thefile1;
	}

	public String getThetitle2() {
		return thetitle2;
	}

	public void setThetitle2(String thetitle2) {
		this.thetitle2 = thetitle2;
	}

	public FormFile getThefile2() {
		return thefile2;
	}

	public void setThefile2(FormFile thefile2) {
		this.thefile2 = thefile2;
	}

	public String getThetitle3() {
		return thetitle3;
	}

	public void setThetitle3(String thetitle3) {
		this.thetitle3 = thetitle3;
	}

	public FormFile getThefile3() {
		return thefile3;
	}

	public void setThefile3(FormFile thefile3) {
		this.thefile3 = thefile3;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}