/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.action;

import hibernate.Bulletin;

import java.sql.Timestamp;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dlpu.eva.file.FileNameFactory;
import com.dlpu.eva.file.FileOperate;
import com.dlpu.eva.service.BulletinService;
import com.dlpu.eva.service.GetSourceUrlService;
import com.dlpu.eva.struts.form.BulletinuploadForm;
import com.dlpu.eva.time.GetSystemTime;

/**
 * MyEclipse Struts Creation date: 10-28-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/bulletinupload" name="bulletinuploadForm"
 *                scope="request"
 */
@Entity
public class BulletinuploadAction extends Action {
	/*
	 * Generated Methods
	 */
	private static final String SUCCESS = "success";
	private static final String ERROR = "error";
	private static final String FERROR = "fileerror";
	private static final String DERROR = "dataerror";

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		BulletinuploadForm bulletinuploadForm = (BulletinuploadForm) form;
		Object s = request.getSession().getAttribute("adminuser");
		if (s == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}

		BulletinService bs = new BulletinService();
		Bulletin b = new Bulletin();

		// ��ȡ��ǰϵͳʱ��(��ȷ����)��Ϊ���ű��
		GetSystemTime gst = new GetSystemTime();
		String lt = gst.GetFullTimeSQLHelper();
		Timestamp timestamp = gst.GetFullTimeStamp();

		b.setBulletinid(lt);
		b.setBulletindate(timestamp);
		b.setBulletintitle(bulletinuploadForm.getThetitle());
//		if(bulletinuploadForm.getFiletitle().substring(0, 1).equals(" ") || bulletinuploadForm.getFiletitle().substring(0, 1).equals("")||bulletinuploadForm.getFiletitle().equals(null)){
//			b.setBulletinfilename(bulletinuploadForm.getThetitle());
//		}else{
//			b.setBulletinfilename(bulletinuploadForm.getFiletitle());
//		}
		
		String filenameString = bulletinuploadForm.getThefile().getFileName();
		
		if(!filenameString.equals(null) && !filenameString.equals("")){
			if(bulletinuploadForm.getFiletitle().substring(0, 1).equals(" ") || bulletinuploadForm.getFiletitle().equals("") || bulletinuploadForm.getFiletitle().equals(null)){
				b.setBulletinfilename(filenameString);
			}else{
				b.setBulletinfilename(bulletinuploadForm.getFiletitle());
			}
		}
		
		if (filenameString != null && !filenameString.equals("")) {
			FileNameFactory fnf = new FileNameFactory();
			filenameString = fnf.changeFileName(lt, filenameString);
			if (filenameString == null) {
				return mapping.findForward(FERROR);
			}
		}
		b.setBulletinurl(filenameString);
		if (b.getBulletinurl() != null && !b.getBulletinurl().equals("")) {// ����и������ϴ���Ƭ
			GetSourceUrlService gsus = new GetSourceUrlService();
			FileOperate fo = new FileOperate();
			if (!fo.AddOneFile(gsus.GetBulletinfileURL(), b.getBulletinurl(), bulletinuploadForm.getThefile())) {
				return mapping.findForward(FERROR);
			}
		}
		if (bs.AddOneBulletin(b)) {
			return mapping.findForward(SUCCESS);
		} else {
			return mapping.findForward(DERROR);
		}
	}
}