/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.action;

import hibernate.Downfile;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dlpu.eva.file.FileNameFactory;
import com.dlpu.eva.file.FileOperate;
import com.dlpu.eva.service.DownfileService;
import com.dlpu.eva.service.GetSourceUrlService;
import com.dlpu.eva.struts.form.DownfileuploadForm;
import com.dlpu.eva.time.GetSystemTime;

/**
 * MyEclipse Struts Creation date: 10-28-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/downfilechange" name="downfileuploadForm"
 *                scope="request"
 */
@Entity
public class DownfilechangeAction extends Action {
	/*
	 * Generated Methods
	 */
	private static final String SUCCESS = "success";
	private static final String ERROR = "error";
	private static final String FERROR = "fileerror";
	private static final String DERROR = "dataerror";

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		DownfileuploadForm downfileuploadForm = (DownfileuploadForm) form;
		Object s = request.getSession().getAttribute("adminuser");
		if (s == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}
		
		String id = request.getParameter("id");
		if (id == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}
		
		DownfileService dfs = new DownfileService();
		Downfile d = new Downfile();
		Downfile orgf = dfs.GetDownfileById(id);

		d.setFileid(id);
//		if(downfileuploadForm.getThetitle().substring(0, 1).equals(" ") || downfileuploadForm.getThetitle().substring(0, 1).equals("")||downfileuploadForm.getThetitle().equals(null)){
//			d.setFilename(downfileuploadForm.getThefile().getFileName());
//		}else{
//			d.setFilename(downfileuploadForm.getThetitle());
//		}
		
		String filenameString = downfileuploadForm.getThefile().getFileName();
		
		if(!filenameString.equals(null) && !filenameString.equals("")){
			if(downfileuploadForm.getThetitle().substring(0, 1).equals(" ") || downfileuploadForm.getThetitle().equals("") || downfileuploadForm.getThetitle().equals(null)){
				d.setFilename(filenameString);
			}else{
				d.setFilename(downfileuploadForm.getThetitle());
			}
		}
		
		if (filenameString != null && !filenameString.equals("")) {
			FileNameFactory fnf = new FileNameFactory();
			filenameString = fnf.changeFileName(id, filenameString);
			if (filenameString == null) {
				return mapping.findForward(FERROR);
			}
			d.setFileurl(filenameString);
			GetSourceUrlService gsus = new GetSourceUrlService();
			FileOperate fo = new FileOperate();
			fo.DelOneFile(gsus.GetDownfileURL(), orgf.getFileurl(), false);
			if (!fo.AddOneFile(gsus.GetDownfileURL(), d.getFileurl(), downfileuploadForm.getThefile())) {
				return mapping.findForward(FERROR);
			}
		} else {
			d.setFileurl(orgf.getFileurl());
		}

		if (dfs.UpdateDownfile(d)) {
			return mapping.findForward(SUCCESS);
		} else {
			return mapping.findForward(DERROR);
		}
	}
}