/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.action;

import hibernate.Eva;

import java.sql.Timestamp;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dlpu.eva.file.FileNameFactory;
import com.dlpu.eva.file.FileOperate;
import com.dlpu.eva.service.EvaService;
import com.dlpu.eva.service.GetSourceUrlService;
import com.dlpu.eva.struts.form.EvauploadForm;
import com.dlpu.eva.time.GetSystemTime;

/**
 * MyEclipse Struts Creation date: 10-27-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/evaupload" name="evauploadForm" scope="request"
 */
@Entity
public class EvauploadAction extends Action {
	/*
	 * Generated Methods
	 */
	private static final String SUCCESS = "success";
	private static final String ERROR = "error";
	private static final String FERROR = "fileerror";
	private static final String DERROR = "dataerror";

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		EvauploadForm evauploadForm = (EvauploadForm) form;
		Object s = request.getSession().getAttribute("adminuser");
		if (s == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}

		EvaService es = new EvaService();
		Eva e = new Eva();

		// ��ȡ��ǰϵͳʱ��(��ȷ����)��Ϊ���ű��
		GetSystemTime gst = new GetSystemTime();
		String lt = gst.GetFullTimeSQLHelper();
		Timestamp timestamp = gst.GetFullTimeStamp();

		e.setEvaid(lt);
		e.setEvadate(timestamp);
		e.setEvatitle(evauploadForm.getThetitle());
//		if(evauploadForm.getFiletitle().substring(0, 1).equals(" ") || evauploadForm.getFiletitle().substring(0, 1).equals("")||evauploadForm.getFiletitle().equals(null)){
//			e.setEvafilename(evauploadForm.getThetitle());
//		}else{
//			e.setEvafilename(evauploadForm.getFiletitle());
//		}
		
		String filenameString = evauploadForm.getThefile().getFileName();
		
		if(!filenameString.equals(null) && !filenameString.equals("")){
			if(evauploadForm.getFiletitle().substring(0, 1).equals(" ") || evauploadForm.getFiletitle().equals("") || evauploadForm.getFiletitle().equals(null)){
				e.setEvafilename(filenameString);
			}else{
				e.setEvafilename(evauploadForm.getFiletitle());
			}
		}
		
		if (filenameString != null && !filenameString.equals("")) {
			FileNameFactory fnf = new FileNameFactory();
			filenameString = fnf.changeFileName(lt, filenameString);
			if (filenameString == null) {
				return mapping.findForward(FERROR);
			}
		}
		e.setEvaurl(filenameString);
		if (e.getEvaurl() != null && !e.getEvaurl().equals("")) {// ����и������ϴ���Ƭ
			GetSourceUrlService gsus = new GetSourceUrlService();
			FileOperate fo = new FileOperate();
			if (!fo.AddOneFile(gsus.GetEvafileURL(), e.getEvaurl(), evauploadForm.getThefile())) {
				return mapping.findForward(FERROR);
			}
		}
		if (es.AddOneEva(e)) {
			return mapping.findForward(SUCCESS);
		} else {
			return mapping.findForward(DERROR);
		}
	}
}