/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.action;

import hibernate.Admin;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dlpu.eva.service.AdminService;
import com.dlpu.eva.struts.form.LoginForm;

/**
 * MyEclipse Struts Creation date: 10-22-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action
 */
@Entity
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */
	private static final String SUCCESS = "success";
	private static final String FAIL = "fail";

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		LoginForm af = (LoginForm) form;
		AdminService as = new AdminService();
		Admin a = new Admin();
		a.setUsername(af.getUsername());
		a.setPassword(af.getPassword());
		if (as.CheckAdmin(a)) {
			request.getSession().setAttribute("adminuser", a.getUsername());
			return mapping.findForward(SUCCESS);
		} else {
			return mapping.findForward(FAIL);
		}
	}
}