/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.action;

import java.sql.Timestamp;

import hibernate.News;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dlpu.eva.file.FileNameFactory;
import com.dlpu.eva.file.FileOperate;
import com.dlpu.eva.service.GetSourceUrlService;
import com.dlpu.eva.service.NewsService;
import com.dlpu.eva.struts.form.NewsuploadForm;
import com.dlpu.eva.time.GetSystemTime;

/**
 * MyEclipse Struts Creation date: 10-22-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/newsupload" name="newsuploadForm"
 *                input="/administrator/upload/newsupload.jsp" scope="request"
 * @struts.action-forward name="fail" path="/administrator/reply.jsp?type=error"
 *                        redirect="true"
 * @struts.action-forward name="success"
 *                        path="/administrator/reply.jsp?type=true"
 *                        redirect="true"
 */
@Entity
public class NewsuploadAction extends Action {
	/*
	 * Generated Methods
	 */
	private static final String SUCCESS = "success";
	private static final String ERROR = "error";
	private static final String FERROR = "fileerror";
	private static final String DERROR = "dataerror";

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		Object s = request.getSession().getAttribute("adminuser");
		if (s == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}
		NewsuploadForm newsuploadForm = (NewsuploadForm) form;
		News n = new News();

		// ��ȡ��ǰϵͳʱ��(��ȷ����)��Ϊ���ű��
		GetSystemTime gst = new GetSystemTime();
		String lt = gst.GetFullTimeSQLHelper();
		Timestamp tsTimestamp = gst.GetFullTimeStamp();

		// ����µ�������Դ�����ݿ�
		n.setNewsid(lt);
		n.setNewstitle(newsuploadForm.getNewstitle());
		n.setNewscontent(newsuploadForm.getMytext());
		
		n.setNewsfiletitle(newsuploadForm.getImgtitle());
		n.setNewstime(tsTimestamp);
		String filenameString = newsuploadForm.getImgfile().getFileName();
		if (filenameString != null && !filenameString.equals("")) {
			FileNameFactory fnf = new FileNameFactory();
			filenameString = fnf.changeFileName(lt, filenameString);
			if (filenameString == null) {
				return mapping.findForward(FERROR);
			}
			n.setNewsfileurl(filenameString);
			// ȡ���ļ������Ӧ�ĵ�ַ
			GetSourceUrlService gsurl = new GetSourceUrlService();
			FileOperate fo = new FileOperate();
			if (!fo.AddOneFile(gsurl.GetNewsFileUrl(), filenameString, newsuploadForm.getImgfile())) {
				return mapping.findForward(FERROR);// ��Ƭ�ϴ�ʧ�ܴ���
			}
		}

		// ����һ������
		NewsService ns = new NewsService();
		if (ns.AddOneNews(n)) {
			return mapping.findForward(SUCCESS);
		} else {
			return mapping.findForward(DERROR);
		}

	}
}