/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.action;

import hibernate.Quality;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dlpu.eva.file.FileNameFactory;
import com.dlpu.eva.file.FileOperate;
import com.dlpu.eva.service.GetSourceUrlService;
import com.dlpu.eva.service.QualityService;
import com.dlpu.eva.struts.form.QualityuploadForm;

/**
 * MyEclipse Struts Creation date: 10-27-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/qualitychange" name="qualityuploadForm" scope="request"
 */
@Entity
public class QualitychangeAction extends Action {
	/*
	 * Generated Methods
	 */
	private static final String SUCCESS = "success";
	private static final String ERROR = "error";
	private static final String FERROR = "fileerror";
	private static final String DERROR = "dataerror";

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		QualityuploadForm qualityuploadForm = (QualityuploadForm) form;
		Object s = request.getSession().getAttribute("adminuser");
		if (s == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}

		String id = request.getParameter("id");
		if (id == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}

		QualityService qs = new QualityService();
		Quality q = new Quality();
		Quality orgq = qs.GetQuaById(id);

		q.setQuaid(id);
		q.setQuatitle(qualityuploadForm.getQuatitle());
//		if(qualityuploadForm.getFiletitle().substring(0, 1).equals(" ") || qualityuploadForm.getFiletitle().substring(0, 1).equals("")||qualityuploadForm.getFiletitle().equals(null)){
//			q.setQuafilename(qualityuploadForm.getQuatitle());
//		}else{
//			q.setQuafilename(qualityuploadForm.getFiletitle());
//		}
		//q.setQuafilename(qualityuploadForm.getFiletitle());
		q.setQuadate(orgq.getQuadate());
		q.setQuatype(qualityuploadForm.getQuatype());
		String filenameString = qualityuploadForm.getQuafile().getFileName();
		
		if(!filenameString.equals(null) && !filenameString.equals("")){
			if(qualityuploadForm.getFiletitle().substring(0, 1).equals(" ") || qualityuploadForm.getFiletitle().equals("") || qualityuploadForm.getFiletitle().equals(null)){
				q.setQuafilename(filenameString);
			}else{
				q.setQuafilename(qualityuploadForm.getFiletitle());
			}
		}
		
		if (filenameString != null && !filenameString.equals("")) {
			FileNameFactory fnf = new FileNameFactory();
			filenameString = fnf.changeFileName(id, filenameString);
			if (filenameString == null) {
				return mapping.findForward(FERROR);
			}
			q.setQuaurl(filenameString);
			// ȡ���ļ������Ӧ�ĵ�ַ
			GetSourceUrlService gsus = new GetSourceUrlService();
			FileOperate fo = new FileOperate();
			fo.DelOneFile(gsus.GetQualityFileURL(), orgq.getQuaurl(), false);// ɾ��ԭ���ĸ���
			if (!fo.AddOneFile(gsus.GetPolicyFileURL(), q.getQuaurl(), qualityuploadForm.getQuafile())) {
				return mapping.findForward(FERROR);
			}
		} else {
			q.setQuaurl(orgq.getQuaurl());
		}

		if (qs.UpdateQuailty(q)) {
			return mapping.findForward(SUCCESS);
		} else {
			return mapping.findForward(DERROR);
		}
	}
}