/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.dlpu.eva.struts.action;

import java.sql.Timestamp;

import hibernate.Schoolfile;

import javax.persistence.Entity;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.dlpu.eva.file.FileNameFactory;
import com.dlpu.eva.file.FileOperate;
import com.dlpu.eva.service.GetSourceUrlService;
import com.dlpu.eva.service.SchoolfileService;
import com.dlpu.eva.struts.form.SchoolfileuploadForm;
import com.dlpu.eva.time.GetSystemTime;

/**
 * MyEclipse Struts Creation date: 10-27-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/schoolfilechange" name="schoolfileuploadForm"
 *                scope="request"
 */
@Entity
public class SchoolfilechangeAction extends Action {
	/*
	 * Generated Methods
	 */
	private static final String SUCCESS = "success";
	private static final String ERROR = "error";
	private static final String FERROR = "fileerror";
	private static final String DERROR = "dataerror";

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {
		SchoolfileuploadForm schoolfileuploadForm = (SchoolfileuploadForm) form;
		Object s = request.getSession().getAttribute("adminuser");
		if (s == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}

		String id = request.getParameter("id");
		if (id == null) {// ��ֹ����
			return mapping.findForward(ERROR);
		}

		GetSystemTime gst = new GetSystemTime();
		SchoolfileService ss = new SchoolfileService();
		Schoolfile schoolfile = new Schoolfile();
		Schoolfile orgs = ss.GetSchoolfileById(id);

		schoolfile.setFileid(id);
		schoolfile.setFiletitle(schoolfileuploadForm.getThetitle());
//		if(schoolfileuploadForm.getFiletitle().substring(0, 1).equals(" ") || schoolfileuploadForm.getFiletitle().substring(0, 1).equals("")||schoolfileuploadForm.getFiletitle().equals(null)){
//			schoolfile.setFilename(schoolfileuploadForm.getThetitle());
//		}else{
//			schoolfile.setFilename(schoolfileuploadForm.getFiletitle());
//		}
		//schoolfile.setFilename(schoolfileuploadForm.getFiletitle());
		//Timestamp timestamp = gst.GetFullTimeStamp(schoolfileuploadForm.getThedate());
		schoolfile.setFilenumber(schoolfileuploadForm.getThenumber());
		schoolfile.setFiledate(schoolfileuploadForm.getThedate());
		schoolfile.setFilecontent(schoolfileuploadForm.getMytext());
		String filenameString = schoolfileuploadForm.getThefile().getFileName();
		
		if(!filenameString.equals(null) && !filenameString.equals("")){
			if(schoolfileuploadForm.getFiletitle().substring(0, 1).equals(" ") || schoolfileuploadForm.getFiletitle().equals("") || schoolfileuploadForm.getFiletitle().equals(null)){
				schoolfile.setFilename(filenameString);
			}else{
				schoolfile.setFilename(schoolfileuploadForm.getFiletitle());
			}
		}
		
		if (filenameString != null && !filenameString.equals("")) {
			FileNameFactory fnf = new FileNameFactory();
			filenameString = fnf.changeFileName(id, filenameString);
			if (filenameString == null) {
				return mapping.findForward(FERROR);
			}
			schoolfile.setFileurl(filenameString);
			// ȡ���ļ������Ӧ�ĵ�ַ
			GetSourceUrlService gsus = new GetSourceUrlService();
			FileOperate fo = new FileOperate();
			fo.DelOneFile(gsus.GetSchoolfileURL(), orgs.getFileurl(), false);// ɾ��ԭ���ĸ���
			if (!fo.AddOneFile(gsus.GetSchoolfileURL(), schoolfile.getFileurl(), schoolfileuploadForm.getThefile())) {
				return mapping.findForward(FERROR);
			}
		} else {
			schoolfile.setFileurl(orgs.getFileurl());
		}

		if (ss.UpdateSchoolfile(schoolfile)) {
			return mapping.findForward(SUCCESS);
		} else {
			return mapping.findForward(DERROR);
		}
	}
}